import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./global.css";

const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={`${roboto.className} h-full antialiased`}
    >
      <head>
        
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
